language: c

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.5-linux64.tar.xz
  - tar xf arduino-1.8.5-linux64.tar.xz
  - sudo mv arduino-1.8.5 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
  
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/MPU9255-Arduino-Librar

script:
  - arduino --verify --board arduino:avr:uno $PWD/examples/dataProcessing/dataProcessing.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/rawData/rawData.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/scaleExample/scaleExample.ino
